### ISSUE TITLE
[Feature Request] Support for "Expanded Storage"

### ISSUE THREAD

**Issue by CalamitousEnd** [CrimsonFluff/Silk-Chests#1]
I'm willing to also try and help you out with this as well if I can but I am really interested in the idea of this mod working with the Expanded Storage Mod.

https://www.curseforge.com/minecraft/mc-mods/expanded-storage-forge

**Comment by CrimsonFluff** [comment]
The mod needs re-writing because it is not compatible with mods like FTB Chunks.  So I will be adding a tool to break blocks.  Basically when the tool breaks any block it just saves the nbt to the item.  Its quite simple
Same with the Silk Spawners mod

But im trying to fix my Harvester mod, and have just updated Crimson Chickens for Fabric too

Takes a lot of time

**Comment by CalamitousEnd** [comment]
All right, may I see the code for this mod? All I see is just the readme?

**Comment by CalamitousEnd** [comment]
So, it's no longer going to be dependent on the silk touch enchantment?

**Comment by CrimsonFluff** [comment]
so basically we cant use the Break Block event, because it can over ride mods like FTB Chunks, chunk protection and/or mods that break blocks themselves, like Refined Storage/AE2 etc

the best way to do it is by having a tool or object. Like Cyclics magic Sack or Mekanisms Cardboard Box
We can make a custom tool that requires silk-touch. But im not sure which route to take

**Comment by CrimsonFluff** [comment]
code is uploaded for 1.16.5 Forge

**Comment by CrimsonFluff** [comment]
updated: should support any tile entity (chest, furnace, barrel, machine etc)
silly thing is I made this 3 weeks ago and lost the code   ;-)

**Comment by CalamitousEnd** [comment]
So...The 1.16.5 version is supposed to work with all Tile Entities?

**Comment by CrimsonFluff** [comment]
the code I uploaded a couple hours ago is, yes.  its only tested with furnaces, chests and barrels

Barrels place the wrong way, not sure whats going on there

**Comment by CalamitousEnd** [comment]
All right, really excited, I cannot wait to see the 1.17 version on curseforge. Honestly, I love the Silk Touch Idea better than using a special tool or something to pick up the saved data. :)

**Comment by CrimsonFluff** [comment]
new versions waiting for CurseForge approval (1.16.5 and 1.17.1)
changed mod name too

https://www.curseforge.com/minecraft/mc-mods/crimson-silky-touch

**Comment by CalamitousEnd** [comment]
Will do. One final thing. Do I still need to have the Silk Spawners mod or is this kind of a solution to both mods?

**Comment by CrimsonFluff** [comment]
I havnt tested this mod with spawners. 

The Silk Spawners mod displays custom spawner tooltips which Silky Touch does not.  But I could combine the two into a single mod

**Comment by CalamitousEnd** [comment]
Please do. :)

**Comment by CalamitousEnd** [comment]
Just a heads up, the mod works with everything that is a Tile Entity now, modded or not modded. Thank you so much! It works flawlessly with Expanded Storage, Easy Magic, and Vanilla. Which are what I tested.
